### ISSUE TITLE
Update code to use bycycle instead of neurodsp

### ISSUE THREAD

**Issue by srcole** [voytekresearch/Cole_2018_cyclebycycle#1]
bycycle (https://github.com/voytekresearch/bycycle) is the new library to be used for waveform shape analysis.

This analysis was moved out of neurodsp (https://github.com/voytekresearch/neurodsp), which is meant as a collection of miscellaneous functions for doing spectral analysis on neural signals.

**Comment by TomDonoghue** [comment]
@srcole Do you know if we have a tagged version of NDSP that has the shape stuff, and would make this repository run-able? Unless you're planning on doing it anyways, literally updating this to use ByCycle seems like a lot, but if we could say something like requires:
neurodsp == 0.1.0
Then at least people could re-run this, if they really wanted to.

**Comment by srcole** [comment]
right. It's in the v2 branch (current draft). I guess I should make that clear. I'm hesitant to merge it into master right now because many figures are now different than the current biorxiv version. Or I guess we could update the version on biorxiv.

**Comment by srcole** [comment]
Just now updated master to reflect the final version of the paper. I added a note to the readme about neurodsp being written in v 1.0.1, and it is specified in the environment file (did you do that? did I do that? I don't remember anything anymore).

So I think we can close this issue
